### ISSUE TITLE
422 status from Hex - Validation Failed

### ISSUE THREAD

**Issue by olivierdupuis** [hex-inc/dagster-hex#2]
I should first mention that this might just be an issue with my own implementation, but I unfortunately cannot find a good way to trace the error at its root and get to the actual issue.

I have an open-source project where I'm trying to leverage the `dagster-hex` library to eventually automatically refresh my Hex notebook once my data warehouse has been rebuilt. You can see [my implementation here](https://github.com/lantrns-analytics/discursus_data_platform/blob/62_hex_refresh/discursus_data_platform/assets/dw_assets.py), starting at line 105:

```python
@asset(
    #non_argument_deps = {"dw_data_tests"},
    description = "Hex project refresh",
    group_name = "data_apps",
    resource_defs = {
        'hex_resource': resources.my_resources.my_hex_resource
    },
)
def hex_project_refresh(context):
    hex_output: HexOutput = context.resources.hex_resource.run_and_poll(
        project_id = "d6824152-38b4-4f39-8f5e-c3a963cc48c8",
        inputs = None,
        update_cache = False,
        kill_on_timeout = True,
        poll_interval = DEFAULT_POLL_INTERVAL,
        poll_timeout = None,
    )
    asset_name = ["hex", hex_output.run_response["projectId"]]

    return Output(
        value = asset_name, 
        metadata={
            "run_url": MetadataValue.url(hex_output.run_response["runUrl"]),
            "run_status_url": MetadataValue.url(
                hex_output.run_response["runStatusUrl"]
            ),
            "trace_id": MetadataValue.text(hex_output.run_response["traceId"]),
            "run_id": MetadataValue.text(hex_output.run_response["runId"]),
            "elapsed_time": MetadataValue.int(
                hex_output.status_response["elapsedTime"]
            ),
        },
    )
```

It should be noted that the implementation doesn't follow the README instructions as I instead want to have the `op` as a software-defined asset instead. That said, I did also a parallel implementation that followed the instructions to the letter, and I still end up with the same issue.

My environment details:
- The latest version of the `dagster-hex` library
- Dagster version 1.0.12
- Project is contained within a Docker image that is ran on a AWS ec2 linux instance

When I launch the `refresh_hex_job`...
<img width="902" alt="Screen Shot 2022-10-27 at 09 07 16" src="https://user-images.githubusercontent.com/20470/198292832-c5e95979-3165-4ac1-9f76-100b1f39a938.png">

I get the following error...
<img width="1031" alt="Screen Shot 2022-10-27 at 09 08 02" src="https://user-images.githubusercontent.com/20470/198292966-72c839e0-8584-49a1-87b0-491e7193060f.png">

Additionally, [my `hex` resource is defined](https://github.com/lantrns-analytics/discursus_data_platform/blob/62_hex_refresh/discursus_data_platform/resources/my_resources.py) on line 29 of this file...

```python
from dagster_hex.resources import hex_resource 
hex_configs = config_from_files(['configs/hex_configs.yaml'])
my_hex_resource = hex_resource.configured(hex_configs)
```

The config used to initiate my resource looks like...

```
api_key: 
  env: HEX_API_KEY
```

The `HEX_API_KEY` environment variable is defined in my Dockerfile.

Please let me know if you need more info. Thank you!

**Comment by maclockard** [comment]
@olivierdupuis My current suspicion is that we might have a bug with how we handle the optionality of the `inputs` parameter. Can you try passing an empty dictionary for `inputs` instead?

**Comment by olivierdupuis** [comment]
@maclockard Thanks for this, that seems to have solved the issue. I successfully ran a refresh job 🙌 

<img width="1294" alt="Screen Shot 2022-10-27 at 12 33 07" src="https://user-images.githubusercontent.com/20470/198347696-f1e52ec4-fd55-4de9-9845-f7d4abda6ee1.png">

Let me know if you want me to raise a PR which defaults the inputs to an empty dictionary in the library's op definition.

**Comment by maclockard** [comment]
That's great! I think we need to figure out how exactly we want this parameter to be nullable. We will try to fix it soon!

**Comment by olivierdupuis** [comment]
Hey @maclockard , I think I'm hitting an issue that is directly related to the above. I made some changes to my API call so that it would also refresh the app's cache once completed. 

Unfortunately, once I change the `update_cache` parameter to `True`, it gives me the following error: `Received 422 status from Hex: {'reason': 'Cannot update the cache if specifying custom input parameters'`

Considering that based on solution above I'm now passing an empty dictionary for `inputs`, it does seem like the API cannot handle that type of request.

My Dagster asset definition now looks like this.

```
@asset(
    non_argument_deps = {"dw_data_tests"},
    description = "Hex project refresh",
    group_name = "data_apps",
    resource_defs = {
        'hex_resource': resources.my_resources.my_hex_resource
    },
)
def hex_project_refresh(context):
    hex_output: HexOutput = context.resources.hex_resource.run_and_poll(
        project_id = "d6824152-38b4-4f39-8f5e-c3a963cc48c8",
        inputs = {},
        update_cache = True,
        kill_on_timeout = True,
        poll_interval = DEFAULT_POLL_INTERVAL,
        poll_timeout = None,
    )
    asset_name = ["hex", hex_output.run_response["projectId"]]

    return Output(
        value = asset_name, 
        metadata = {
            "run_url": MetadataValue.url(hex_output.run_response["runUrl"]),
            "run_status_url": MetadataValue.url(
                hex_output.run_response["runStatusUrl"]
            ),
            "trace_id": MetadataValue.text(hex_output.run_response["traceId"]),
            "run_id": MetadataValue.text(hex_output.run_response["runId"]),
            "elapsed_time": MetadataValue.int(
                hex_output.status_response["elapsedTime"]
            ),
        },
    )
```

Let me know fi you need additional information.

Thanks!

**Comment by PedramNavid** [comment]
hey @olivierdupuis just pushed a fix and added some tests, let us know if the latest release (0.1.2) fixes this for you.

**Comment by olivierdupuis** [comment]
There you go, that seems to have solved the issue. Only change I had to do was to change back my `inputs` parameter to `None` instead of an empty dictionary. Thank you all for your help :)

<img width="1187" alt="Screenshot 2022-11-08 at 14 18 25" src="https://user-images.githubusercontent.com/20470/200655632-9028f904-6e0e-4cef-8e27-27dc5b82f144.png">
